# This is the default values file, which should be treated as a template. Values should only be defined
# here if they are shared accross all non-local environments. However, list and comment on all potential values.

api:
  uvicorn:
    autoreload: false
    workers: 16
    port: 8000
    domainSocket: uvicorn-api.sock
    logColors: false
  nginx:
    use: true
    port: 80
  http:
    httpPort: 80
    httpsPort: 443
  # Configurations for setting up apm tracing
  apm:
    enable: false
    datadogTraceAgentHostname: datadog-agent.kube-system
    datadogEnv:
  # The liveness probe will restart the pod if it detects that it is unhealty
  liveness:
    use: true
    # number of seconds before the first probe
    initialDelay: 15
    # number of seconds for frequency between probes
    period: 120
  # The readiness probe will hold off traffic and wait until the pod is ready
  readiness:
    use: true
    initialDelay: 5
    period: 60

deploy:
  # The number of seconds for the containers to perform a graceful shutdown,
  # after which it is violently terminated
  terminationGracePeriod: 50
  replicas: 1

redis:
  create: false
  port: 6379
  containerPort: 6379
  liveness:
    use: true
    initialDelay: 10
    period: 15
  readiness:
    use: true
    initialDelay: 5
    period: 10

elasticsearch:
  create: false
  populate: false
  # The elasticsearch config file is chown'd to the user of this id
  # 1000 is the uid of the first non-root user created, in our case that is the elasticsearch user
  id: 1000
  port: 9200
  containerPort: 9200
  storage: 1Gi
  liveness:
    use: true
    initialDelay: 10
    period: 60
  readiness:
    use: true
    initialDelay: 10
    period: 30

rbac:
  enabled: true
